version: 2

sources:
  - name: bronze
    database: iceberg
    schema: bronze
    tables:
      - name: mes_events
      - name: mes_production_orders
      - name: iqms_deviations
      - name: iqms_orders
      - name: iqms_quality_tests
      - name: tms_training_completions
      - name: trackwise_capas
      - name: trackwise_deviations
      - name: sap_ecc_orders
      - name: sop_documents
