apiVersion: 1

datasources:
  - name: Prometheus
    uid: tpl-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    uid: tpl-loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: PostgreSQL
    uid: tpl-postgres
    type: postgres
    url: postgres:5432
    database: lakehouse_meta
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: disable

  - name: Trino
    uid: tpl-trino
    type: trino-datasource
    url: http://trino:8080
    user: admin

  - name: PostgreSQL (Airflow)
    uid: tpl-postgres-airflow
    type: postgres
    url: postgres:5432
    database: airflow
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      sslmode: disable
